#!/bin/bash -l
#$ -S /bin/bash
#$ -cwd
#$ -j y
#$ -m eas
#$ -o nextflow.log
#$ -N nextflow
#$ -l h_rt=150:00:00
#$ -l mem_free=5g

# Parse command-line argument
config_filename="${1}"

# Load and list modules
module load nextflow
module list
export NXF_ENABLE_SECRETS=true
# Note: this command expects RNA_Seq.nf to be in the current working directory
nextflow -C "${config_filename}" \
         run -w /work RNA_Seq.nf \
         -with-trace 
